//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeferredObjectMaterialization.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOMEntities : DbContext
    {
        public DOMEntities()
            : base("name=DOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PaymentGateway> PaymentGateways { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductPaymentGateway> ProductPaymentGateways { get; set; }
    }
}
