//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeferredObjectMaterialization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public PaymentGateway()
        {
            this.ProductPaymentGateways = new HashSet<ProductPaymentGateway>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public string AppId { get; set; }
        public string AppKey { get; set; }
    
        public virtual ICollection<ProductPaymentGateway> ProductPaymentGateways { get; set; }
    }
}
